elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
  hostname: logstash
# Apparently logspout needs to either start first or all other
# containers need to be restarted after it's up for it to get logs
# since we don't actually want the logs of the logstash instance (or do we?)
logspout:
  build: logspout/
  environment:
    - DEBUG=true
    - ROUTE_URIS=logstash://logstash:5000
  volumes: 
   - /var/run/docker.sock:/tmp/docker.sock
  links:
    -  logstash
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch