elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
  restart: always  
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  expose:
    - 5000/udp  
  environment:
    - LOGSPOUT=ignore
  links:
    - elasticsearch
  hostname: logstash
# Apparently logspout needs to either start first or all other
# containers need to be restarted after it's up for it to get logs
# since we don't actually want the logs of the logstash instance (or do we?)
logspout:
  build: logspout/
  command: logstash://logstash:5000
  volumes: 
   - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - DEBUG=true
  links:
    -  logstash
  restart: always  
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch